# Generated by Django 2.1.3 on 2019-05-01 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('year', models.IntegerField(default=None)),
                ('rated', models.CharField(default='N/A', max_length=10)),
                ('released', models.DateField(default=None)),
                ('runtime', models.IntegerField(default=None)),
                ('genre', models.CharField(default='N/A', max_length=100)),
                ('director', models.CharField(default='N/A', max_length=100)),
                ('writer', models.CharField(default='N/A', max_length=100)),
                ('actors', models.CharField(default='N/A', max_length=5000)),
                ('plot', models.TextField()),
                ('language', models.CharField(default='N/A', max_length=100)),
                ('country', models.CharField(default='N/A', max_length=100)),
                ('awards', models.CharField(default='N/A', max_length=200)),
                ('poster', models.CharField(default='N/A', max_length=200)),
                ('metascore', models.IntegerField(default=None)),
                ('imdbrating', models.DecimalField(decimal_places=1, default=None, max_digits=4)),
                ('imdbvotes', models.IntegerField(default=None)),
                ('imdbid', models.CharField(default='N/A', max_length=20)),
                ('type_picture', models.CharField(default='N/A', max_length=20, verbose_name='type of picture')),
                ('dvd', models.DateField(default=None)),
                ('boxoffice', models.CharField(default='N/A', max_length=20)),
                ('production', models.CharField(default='N/A', max_length=50)),
                ('website', models.CharField(default='N/A', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='N/A', max_length=100)),
                ('value', models.CharField(default='N/A', max_length=20)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='omdbapi.Movie')),
            ],
        ),
    ]
