# Generated by Django 2.1.8 on 2019-05-03 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omdbapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='totalSeasons',
            new_name='totalseasons',
        ),
    ]
